spring.application.name=BBA-BCA-Wallah-JUT
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/bba_bca_wallah?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Kolkata}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:}
spring.jpa.hibernate.ddl-auto=update
spring.thymeleaf.cache=false

app.admin.username=${ADMIN_USERNAME:admin}
app.admin.password=${ADMIN_PASSWORD}
app.upload.dir=${UPLOAD_DIR:uploads}

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
server.port=${PORT:8080}
